### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by kerrycobb** [kerrycobb/BioSeq#11]
@Unaimend 

It is great to see your new additions! With the project growing we might want to have a different strategy for organizing the code. At this time we have the SAM and FASTQ types within the IO directory. Down the road there might be procs that are not related to IO associated with those in which case a directory named IO might not be an intuitive place to look.  I don't have any good idea at the moment but I wanted to start a discussion about it. Perhaps you've already thought about it some?

**Comment by Unaimend** [comment]
yeah, makes sense what you are saying, we should think about a sensible directory structure. We also should maybe make a plan on what we want to include. BAM, C(R)AM(not sure about the name of the 3rd kind of alignment file) should be pretty annoying to implement, especially the indexing. So I am not sure if we want go through with the "pure nim" plan

**Comment by kerrycobb** [comment]
Maybe what makes the most sense for now is to not have any directories and just keep everything in src/bionim/. If the number of files and their contents grow really large in the future, then we can make changes at that time.
